spring:
  application:
    name: "Blog"
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
springdoc:
  swagger-ui:
    path: /custom-docs
